// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	conf "github.com/RedHatInsights/ccx-notification-service/conf"
	mock "github.com/stretchr/testify/mock"

	producer "github.com/RedHatInsights/ccx-notification-service/producer"

	types "github.com/RedHatInsights/ccx-notification-service/types"
)

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Producer) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// New provides a mock function with given fields: configStruct
func (_m *Producer) New(configStruct conf.ConfigStruct) (producer.Producer, error) {
	ret := _m.Called(configStruct)

	var r0 producer.Producer
	if rf, ok := ret.Get(0).(func(conf.ConfigStruct) producer.Producer); ok {
		r0 = rf(configStruct)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(producer.Producer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(conf.ConfigStruct) error); ok {
		r1 = rf(configStruct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProduceMessage provides a mock function with given fields: msg
func (_m *Producer) ProduceMessage(msg types.NotificationMessage) (int32, int64, error) {
	ret := _m.Called(msg)

	var r0 int32
	if rf, ok := ret.Get(0).(func(types.NotificationMessage) int32); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(types.NotificationMessage) int64); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(types.NotificationMessage) error); ok {
		r2 = rf(msg)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewProducer interface {
	mock.TestingT
	Cleanup(func())
}

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProducer(t mockConstructorTestingTNewProducer) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
