{
 "title": "CCX Notification Services",
 "description": "Dashboard for CCX notification services (to-notification-backend and to-service-log)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "app-sre-observability-stage,app-sre-observability-production"
   }
  ]
 },
 "panels": [
  {
   "title": "CCX Notification Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ccx_notification_service_notification_backend_fetch_content_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Notification Backend] Fetch content"
    },
    {
     "expr": "sum(rate(ccx_notification_service_notification_backend_read_report_for_cluster_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Notification Backend] Read reported"
    },
    {
     "expr": "sum(rate(ccx_notification_service_notification_backend_producer_setup_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Notification Backend] Producer setup"
    },
    {
     "expr": "sum(rate(ccx_notification_service_notification_backend_read_cluster_list_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Notification Backend] Read cluster list"
    },
    {
     "expr": "sum(rate(ccx_notification_service_notification_backend_read_report_for_cluster_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Notification Backend] Read report for cluster"
    },
    {
     "expr": "sum(rate(ccx_notification_service_notification_backend_storage_setup_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Notification Backend] Storage setup"
    },
    {
     "expr": "sum(rate(ccx_notification_service_service_log_fetch_content_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Service Log] Fetch content"
    },
    {
     "expr": "sum(rate(ccx_notification_service_service_log_read_report_for_cluster_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Service Log] Read reported"
    },
    {
     "expr": "sum(rate(ccx_notification_service_service_log_producer_setup_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Service Log] Producer setup"
    },
    {
     "expr": "sum(rate(ccx_notification_service_service_log_read_cluster_list_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Service Log] Read cluster list"
    },
    {
     "expr": "sum(rate(ccx_notification_service_service_log_read_report_for_cluster_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Service Log] Read report for cluster"
    },
    {
     "expr": "sum(rate(ccx_notification_service_service_log_storage_setup_errors{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "[Service Log] Storage setup"
    }
   ]
  },
  {
   "title": "Notifications sent per execution",
   "type": "timeseries",
   "description": "Metrics related with notifications",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ccx_notification_service_notification_backend_notification_sent{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "Notification Backend"
    },
    {
     "expr": "sum(rate(ccx_notification_service_service_log_notification_sent{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "Service Log"
    }
   ]
  },
  {
   "title": "High Impact Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(ccx_notification_service_notification_backend_report_with_high_impact{namespace=\"$namespace\"}[15m]))",
     "legendFormat": "__auto",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "sum(rate(ccx_notification_service_service_log_report_with_high_impact{namespace=\"$namespace\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifications not sent - error",
   "type": "timeseries",
   "description": "Notifications not sent due to an error",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(ccx_notification_service_notification_backend_notification_not_sent_error_state{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "Notification Backend"
    },
    {
     "expr": "sum(rate(ccx_notification_service_service_log_notification_not_sent_error_state{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "Service Log"
    }
   ]
  },
  {
   "title": "Notifications not sent - cluster same state",
   "type": "timeseries",
   "description": "The new reports for given cluster contain issues that were already notified",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(ccx_notification_service_notification_backend_notification_not_sent_same_state{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "Notification Backend"
    },
    {
     "expr": "sum(rate(ccx_notification_service_service_log_notification_not_sent_same_state{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "Service Log"
    }
   ]
  }
 ]
}