name: BDD tests

on:
  push:
    # branches: ["master", "main"]
  pull_request:

jobs:
  bdd:
    name: BDD tests
    uses: joselsegura/processing-tools/.github/workflows/bdd.yaml@bdd-notification-service
    with:
      service: notification-service
      use_kafka: true
      use_postgres: true
