name: Go tests

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  gotests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version:
          - "1.22"
          - "1.23"
    name: Tests for Go ${{ matrix.go-version}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Unit tests
        run: env
      - name: Retrieve code coverage
        run: go test -coverprofile coverage.out $(go list ./... | grep -v tests)
      - name: Display code coverage
        run: go tool cover -func=coverage.out
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
