name: Go linters

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  golint:
    runs-on: ubuntu-latest
    name: Linters
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Build project
        run: make
      - name: shellcheck
        run: make shellcheck
      - name: ABC metrics checker
        run: make abcgo
